feat(connector-api): postman collection [CT-1709]
tink-ab/tink-postman pull request #16
Opened 2022-06-20 11:58 UTC by vanjasmailovic

2022-06-20 14:04 UTC, jangillich requested changes
Nice! I had a small comment on that it says "income check" in the description in a lot of places, otherwise looks great to me :)

2022-06-20 14:04 UTC, jangillich commented on Connector API.postman_collection.json
> +				"description": "Welcome to Tink’s Postman collection for Income Check.\n\nFor detailed information on how to use Income Check, visit [Fetch your first Income Check report](https://docs.tink.com/r
It says "income check" here? Is that intended?

2022-06-20 14:24 UTC, vanjasmailovic commented on Connector API.postman_collection.json
> +				"description": "Welcome to Tink’s Postman collection for Income Check.\n\nFor detailed information on how to use Income Check, visit [Fetch your first Income Check report](https://docs.tink.com/r
Good one, will fix

2022-06-20 14:40 UTC, jangillich approved these changes
🥇

2022-06-21 07:19 UTC, vanjasmailovic commented
bors merge

2022-06-21 07:29 UTC, merged